apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: frontend
  name: echo-frontend
  namespace: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - image: xzhu0027/echo-frontend-grpc:namespaced
        name: frontend-grpc
      serviceAccountName: echo-frontend
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: server
  name: echo-server
  namespace: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
  namespace: server
spec:
  clusterIP: 10.96.77.76
  ports:
  - name: server
    port: 9000
    targetPort: 9000
    appProtocol: grpc
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
      - image: xzhu0027/echo-server-grpc:namespaced
        name: server-grpc
      serviceAccountName: echo-server
  selector:
    matchLabels:
      app: server