// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: ping_pb/ping.proto

package ping_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EchoService_PingHello_FullMethodName = "/ping_pb.EchoService/PingHello"
	EchoService_PingWorld_FullMethodName = "/ping_pb.EchoService/PingWorld"
)

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoServiceClient interface {
	PingHello(ctx context.Context, in *PingHelloRequest, opts ...grpc.CallOption) (*PingHelloResponse, error)
	PingWorld(ctx context.Context, in *PingWorldRequest, opts ...grpc.CallOption) (*PingWorldResponse, error)
}

type echoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoServiceClient(cc grpc.ClientConnInterface) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) PingHello(ctx context.Context, in *PingHelloRequest, opts ...grpc.CallOption) (*PingHelloResponse, error) {
	out := new(PingHelloResponse)
	err := c.cc.Invoke(ctx, EchoService_PingHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) PingWorld(ctx context.Context, in *PingWorldRequest, opts ...grpc.CallOption) (*PingWorldResponse, error) {
	out := new(PingWorldResponse)
	err := c.cc.Invoke(ctx, EchoService_PingWorld_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServiceServer is the server API for EchoService service.
// All implementations must embed UnimplementedEchoServiceServer
// for forward compatibility
type EchoServiceServer interface {
	PingHello(context.Context, *PingHelloRequest) (*PingHelloResponse, error)
	PingWorld(context.Context, *PingWorldRequest) (*PingWorldResponse, error)
	mustEmbedUnimplementedEchoServiceServer()
}

// UnimplementedEchoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServiceServer struct {
}

func (UnimplementedEchoServiceServer) PingHello(context.Context, *PingHelloRequest) (*PingHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingHello not implemented")
}
func (UnimplementedEchoServiceServer) PingWorld(context.Context, *PingWorldRequest) (*PingWorldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingWorld not implemented")
}
func (UnimplementedEchoServiceServer) mustEmbedUnimplementedEchoServiceServer() {}

// UnsafeEchoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServiceServer will
// result in compilation errors.
type UnsafeEchoServiceServer interface {
	mustEmbedUnimplementedEchoServiceServer()
}

func RegisterEchoServiceServer(s grpc.ServiceRegistrar, srv EchoServiceServer) {
	s.RegisterService(&EchoService_ServiceDesc, srv)
}

func _EchoService_PingHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).PingHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoService_PingHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).PingHello(ctx, req.(*PingHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_PingWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).PingWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoService_PingWorld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).PingWorld(ctx, req.(*PingWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoService_ServiceDesc is the grpc.ServiceDesc for EchoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ping_pb.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingHello",
			Handler:    _EchoService_PingHello_Handler,
		},
		{
			MethodName: "PingWorld",
			Handler:    _EchoService_PingWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping_pb/ping.proto",
}
