apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: acl-client
spec:
  workloadSelector:
    labels:
      app: frontend
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 8081 # port number of ping
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.wasm
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            name: acl-block-client
            root_id: acl-block-client
            vm_config:
              vm_id: vm.sentinel.acl-block-server
              runtime: envoy.wasm.runtime.v8
              code:
                local:
                  filename: /etc/acl.wasm
              allow_precompiled: false